<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>

<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("Page"); ?>: <?php echo $this->page; ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->searchButton("acl-search"); ?>
					
					<?php echo $this->createButton("acl-create"); ?>
				</div>
			</div> 
            <?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i> 
						<?php if($this->queryParams['aclRoleId']): ?>
							<?php echo $this->translate("No acl rules found using acl role id:"); ?>
							<b><i><?php echo $this->queryParams['aclRoleId']; ?></i></b>
							<?php if($this->queryParams['aclResourceId']): ?>
								<?php echo $this->translate(' and acl resource id:'); ?>
								<b><i><?php echo $this->queryParams['aclResourceId']; ?></i></b>
							<?php endif; ?>
						<?php elseif($this->queryParams['aclResourceId']): ?>
							<?php echo $this->translate("No acl rules found using acl resource id:"); ?>
							<b><i><?php echo $this->queryParams['aclResourceId']; ?></i></b>
						<?php else: ?>
							<?php echo $this->translate("No acl rules found"); ?>
						<?php endif; ?>
					</p>
				</div>
			</div>
			<?php else: ?>
			<div class="box-body  no-padding">
				<div class="row">
					<div class="col-xs-12">
						<table class="table table-bordered table-hover table-striped table-condensed">
							<thead>
								<tr>
                                    <th><?php echo $this->translate("Role"); ?></th>
                                    <th><?php echo $this->translate("Rule"); ?></th>
                                    <th><?php echo $this->translate("Resource"); ?></th>
                                </tr>
							</thead>
							<tbody>
							<?php foreach($this->paginator as $entity): ?>
								<tr>
									<td>
										<a href="<?php echo $this->url("acl-role-view", array("id" => $entity->getAclRoleId())); ?>" title="<?php echo $this->translate("View"); ?>">
											<?php echo ucwords($entity->getRoleEntity()->getAclRoleName());?>
										</a>
									</td>
									<td>
										<a href="<?php echo $this->url("acl-view", array("id" => $entity->getAclId())); ?>" title="<?php echo $this->translate("View")?>">
											<?php echo $this->translate("Allow"); ?>
										</a>
									<td>
										<a href="<?php echo $this->url("acl-resource-view", array("id" => $entity->getAclResourceId())); ?>" title="<?php echo $this->translate("View"); ?>">
											<?php echo $entity->getResourceEntity()->getAclResourceName();?>
										</a>
									</td>
                                </tr>
                            <?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
				
				<div class="row">
					<div class="col-xs-12 text-center">
						<?php echo $this->Paginator(
							$this->itemCountPerPage, 
							$this->itemCount, 
							$this->pageCount, 
                            $this->page, 
                            $this->routeParams,
                            $this->queryParams);
                        ?>
					</div>
				</div>
			</div>
			<?php endif;?>
		</div>
	</div>
</div>

<?php echo $this->aclSearchForm($this->queryParams); ?>